version: "3.7"
services:
  frontend:
    image: docker.io/adinaclaudiatoma/docker-ws-frontend:1.0
    build:
      context: todo-frontend
      # backend port needs to be passed as build arg because it's used in the build/compile stage, not at runtime
      args:
        BACKEND_HOST: localhost
        BACKEND_PORT: 3333
    ports:
      - 8080:80
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    image: docker.io/adinaclaudiatoma/docker-ws-backend:1.0
    build:
      context: todo-backend
    environment:
      PORT: 3333
    ports:
      - 3333:3333
    restart: always
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express

  mongo:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
networks:
  react-express:
  express-mongo: